format = """
[](bg:purple fg:black)\
[  ](bg:purple fg:white)\
$hostname\
[](bg:orange-red fg:purple)\
$directory\
[](fg:orange-red bg:orange)\
$git_branch\
$git_status\
[](fg:orange bg:blue)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$python\
[](fg:blue bg:cyan)\
$docker_context\
[](fg:cyan bg:deep-blue)\
$time\
[ ](fg:deep-blue)\
$sudo\
$status
[❯ ](bold green)\
"""

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = false

# Set 'foo' as custom color palette
palette = 'foo'

# Define custom colors
[palettes.foo]
# Overwrite existing color
black = '#282a36'
blue = '#86bbd8'
gray = '#6272a4'
cyan = '#06969a'
deep-blue = '#33658a'
green = '#50fa7b'
orange = '#fca17d'
orange-red = '#da627d'
purple = '#9a348e'
red = '#ff5555'
white = '#f8f8f2'

# An alternative to the username module which displays a symbol that
# represents the current operating system
[hostname]
disabled = false
format = '[$ssh_symbol on $hostname]($style)'
ssh_only = true
ssh_symbol = '󰌘'
style = "bg:purple"
trim_at = '.companyname.com'

[directory]
format = "[ $path ]($style)"
style = "bg:orange-red"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
format = '[ $symbol ($version) ]($style)'
style = "bg:blue"
symbol = " "

[docker_context]
format = '[ $symbol $context ]($style) $path'
style = "bg:cyan"
symbol = " "

[elixir]
format = '[ $symbol ($version) ]($style)'
style = "bg:blue"
symbol = " "

[elm]
format = '[ $symbol ($version) ]($style)'
style = "bg:blue"
symbol = " "

[git_branch]
format = '[ $symbol $branch ]($style)'
style = "bg:#FCA17D"
symbol = " "

[git_status]
format = '[$all_status$ahead_behind ]($style)'
style = "bg:#FCA17D"

[golang]
format = '[ $symbol ($version) ]($style)'
style = "bg:blue"
symbol = " "

[gradle]
format = '[ $symbol ($version) ]($style)'
style = "bg:blue"

[haskell]
format = '[ $symbol ($version) ]($style)'
style = "bg:blue"
symbol = " "

[java]
format = '[ $symbol ($version) ]($style)'
style = "bg:blue"
symbol = " "

[julia]
format = '[ $symbol ($version) ]($style)'
style = "bg:blue"
symbol = " "

[nodejs]
format = '[ $symbol ($version) ]($style)'
style = "bg:blue"
symbol = " "

[nim]
format = '[ $symbol ($version) ]($style)'
style = "bg:blue"
symbol = "󰆥 "

[rust]
format = '[ $symbol ($version) ]($style)'
style = "bg:blue"
symbol = " "

[scala]
format = '[ $symbol ($version) ]($style)'
style = "bg:blue"
symbol = " "

[python]
format = '[ $symbol ($version) ]($style)'
pyenv_version_name = true
style = "bg:blue"
symbol = ' '

[time]
disabled = false
format = '[   $time ]($style)'
style = "bg:deep-blue"
time_format = "%m/%d %a %R"

[sudo]
disabled = false
format = '[as $symbol]($style)'
style = 'bold green'
symbol = '󰇄  '

[status]
disabled = false
format = '[$symbol$common_meaning$signal_name$maybe_int]($style)'
map_symbol = true
not_executable_symbol = '[ ](red)'
not_found_symbol = '[ ](orange)'
pipestatus = true
sigint_symbol = '[ ](purple)'
signal_symbol = '[󰉁 ](green)'
style = 'bold fg:gray'
success_symbol = '[ ](green)SUCCESS'
symbol = '[ ](red)'
